// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package v1

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

// 已有的错误码
func IsUnlogin(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_UNLOGIN.String() && e.Code == 401
}

// 已有的错误码
func ErrorUnlogin(format string, args ...interface{}) *errors.Error {
	return errors.New(401, ErrorReason_UNLOGIN.String(), fmt.Sprintf(format, args...))
}

// 数据库操作失败
func IsDbFailed(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_DB_FAILED.String() && e.Code == 500
}

// 数据库操作失败
func ErrorDbFailed(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_DB_FAILED.String(), fmt.Sprintf(format, args...))
}

// 雪花算法ID生成失败（如节点ID冲突、时间回拨等）
func IsIdGenerateFailed(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_ID_GENERATE_FAILED.String() && e.Code == 500
}

// 雪花算法ID生成失败（如节点ID冲突、时间回拨等）
func ErrorIdGenerateFailed(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_ID_GENERATE_FAILED.String(), fmt.Sprintf(format, args...))
}

// 订单已评价
func IsOrderReviewed(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_ORDER_REVIEWED.String() && e.Code == 400
}

// 订单已评价
func ErrorOrderReviewed(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_ORDER_REVIEWED.String(), fmt.Sprintf(format, args...))
}

// 评价不存在（查询/修改不存在的评价时）
func IsReviewNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_REVIEW_NOT_FOUND.String() && e.Code == 404
}

// 评价不存在（查询/修改不存在的评价时）
func ErrorReviewNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(404, ErrorReason_REVIEW_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}

// 参数无效（如评分超出1-5范围、内容为空等）
func IsInvalidParam(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_INVALID_PARAM.String() && e.Code == 400
}

// 参数无效（如评分超出1-5范围、内容为空等）
func ErrorInvalidParam(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_INVALID_PARAM.String(), fmt.Sprintf(format, args...))
}

// 评价已被审核（重复提交审核、审核后再次尝试审核时）
func IsReviewAlreadyAudited(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_REVIEW_ALREADY_AUDITED.String() && e.Code == 400
}

// 评价已被审核（重复提交审核、审核后再次尝试审核时）
func ErrorReviewAlreadyAudited(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_REVIEW_ALREADY_AUDITED.String(), fmt.Sprintf(format, args...))
}

// 无评价权限（如非订单所有者尝试评价）
func IsNoReviewPermission(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_NO_REVIEW_PERMISSION.String() && e.Code == 403
}

// 无评价权限（如非订单所有者尝试评价）
func ErrorNoReviewPermission(format string, args ...interface{}) *errors.Error {
	return errors.New(403, ErrorReason_NO_REVIEW_PERMISSION.String(), fmt.Sprintf(format, args...))
}
