// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: review/v1/review_error.proto

package v1

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorReason int32

const (
	// 已有的错误码
	ErrorReason_UNLOGIN                ErrorReason = 0   // 未登录
	ErrorReason_DB_FAILED              ErrorReason = 1   // 数据库操作失败
	ErrorReason_ID_GENERATE_FAILED     ErrorReason = 2   // 雪花算法ID生成失败（如节点ID冲突、时间回拨等）
	ErrorReason_ORDER_REVIEWED         ErrorReason = 100 // 订单已评价
	ErrorReason_REVIEW_NOT_FOUND       ErrorReason = 101 // 评价不存在（查询/修改不存在的评价时）
	ErrorReason_INVALID_PARAM          ErrorReason = 102 // 参数无效（如评分超出1-5范围、内容为空等）
	ErrorReason_REVIEW_ALREADY_AUDITED ErrorReason = 103 // 评价已被审核（重复提交审核、审核后再次尝试审核时）
	ErrorReason_NO_REVIEW_PERMISSION   ErrorReason = 300 // 无评价权限（如非订单所有者尝试评价）
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0:   "UNLOGIN",
		1:   "DB_FAILED",
		2:   "ID_GENERATE_FAILED",
		100: "ORDER_REVIEWED",
		101: "REVIEW_NOT_FOUND",
		102: "INVALID_PARAM",
		103: "REVIEW_ALREADY_AUDITED",
		300: "NO_REVIEW_PERMISSION",
	}
	ErrorReason_value = map[string]int32{
		"UNLOGIN":                0,
		"DB_FAILED":              1,
		"ID_GENERATE_FAILED":     2,
		"ORDER_REVIEWED":         100,
		"REVIEW_NOT_FOUND":       101,
		"INVALID_PARAM":          102,
		"REVIEW_ALREADY_AUDITED": 103,
		"NO_REVIEW_PERMISSION":   300,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_review_v1_review_error_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_review_v1_review_error_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_review_v1_review_error_proto_rawDescGZIP(), []int{0}
}

var File_review_v1_review_error_proto protoreflect.FileDescriptor

const file_review_v1_review_error_proto_rawDesc = "" +
	"\n" +
	"\x1creview/v1/review_error.proto\x12\rapi.review.v1\x1a\x13errors/errors.proto*\xeb\x01\n" +
	"\vErrorReason\x12\x11\n" +
	"\aUNLOGIN\x10\x00\x1a\x04\xa8E\x91\x03\x12\x13\n" +
	"\tDB_FAILED\x10\x01\x1a\x04\xa8E\xf4\x03\x12\x1c\n" +
	"\x12ID_GENERATE_FAILED\x10\x02\x1a\x04\xa8E\xf4\x03\x12\x18\n" +
	"\x0eORDER_REVIEWED\x10d\x1a\x04\xa8E\x90\x03\x12\x1a\n" +
	"\x10REVIEW_NOT_FOUND\x10e\x1a\x04\xa8E\x94\x03\x12\x17\n" +
	"\rINVALID_PARAM\x10f\x1a\x04\xa8E\x90\x03\x12 \n" +
	"\x16REVIEW_ALREADY_AUDITED\x10g\x1a\x04\xa8E\x90\x03\x12\x1f\n" +
	"\x14NO_REVIEW_PERMISSION\x10\xac\x02\x1a\x04\xa8E\x93\x03\x1a\x04\xa0E\xf4\x03B2\n" +
	"\rapi.review.v1P\x01Z\x1freview-service/api/review/v1;v1b\x06proto3"

var (
	file_review_v1_review_error_proto_rawDescOnce sync.Once
	file_review_v1_review_error_proto_rawDescData []byte
)

func file_review_v1_review_error_proto_rawDescGZIP() []byte {
	file_review_v1_review_error_proto_rawDescOnce.Do(func() {
		file_review_v1_review_error_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_review_v1_review_error_proto_rawDesc), len(file_review_v1_review_error_proto_rawDesc)))
	})
	return file_review_v1_review_error_proto_rawDescData
}

var file_review_v1_review_error_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_review_v1_review_error_proto_goTypes = []any{
	(ErrorReason)(0), // 0: api.review.v1.ErrorReason
}
var file_review_v1_review_error_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_review_v1_review_error_proto_init() }
func file_review_v1_review_error_proto_init() {
	if File_review_v1_review_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_review_v1_review_error_proto_rawDesc), len(file_review_v1_review_error_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_review_v1_review_error_proto_goTypes,
		DependencyIndexes: file_review_v1_review_error_proto_depIdxs,
		EnumInfos:         file_review_v1_review_error_proto_enumTypes,
	}.Build()
	File_review_v1_review_error_proto = out.File
	file_review_v1_review_error_proto_goTypes = nil
	file_review_v1_review_error_proto_depIdxs = nil
}
